

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/springcloud2020?useUnicode=true&characterEncoding=utf-8&useSSL=false\
    &serverTimezone=GMT%2B8"
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: WF##(d/SPhNN73xkJ19EjX/EeReDCehLJkbkx0RxLfCWBhrHUaFMWNxNPD7LdyCqzg2Fq)

jasypt:
  encryptor:
    bean: wfEncryptorBean
    property:
      prefix: WF##(
      suffix: )

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl